### ISSUE TITLE
Enable Extensions-Managment

### ISSUE THREAD

**Issue by znegva** [bolt/try-bolt#3]
It is not possible to install Bolt-Extensions
>The extensions directory (`/var/www/html/extensions`) does not exist, or it is not writable. This means that you cannot manage Bolt extensions through the backend; consider managing extensions manually, or changing file permissions to allow Bolt write access to (`/var/www/html/extensions`).

Would be great to be able to try out and test extensions with some clicks.

**Comment by rossriley** [comment]
Thanks for spotting this. The build is now updated so new sites generated will now be able to install extensions from the UI.
